### ISSUE TITLE
Wrong coverage when there's a pytest plugin installed that imports the module that you want to cover

### ISSUE THREAD

**Issue by nelsyeung** [pytest-dev/pytest-cov#587]
# Summary

When there's a pytest plugin installed that imports the module that you want to have coverage, it will not cover that module. However, running `coverage run -m pytest ...` works as expected.

## Expected vs actual result

Expected:
```
src/foo/__init__.py       2      0   100%
```

Actual result:
```
src/foo/__init__.py       2      1    50%
```

# Reproducer

Create `src/foo/__init__.py`:
```python
def foo() -> str:
    return "foo"
```

Create `src/pytest_foo/__init__.py`:
```python
import foo
```

Create `tests/test_foo.py`:
```python
import foo
def test_foo():
    assert foo.foo() == "foo"
```

I'm using poetry for the build, so in my `pyproject.toml` I have:
```toml
[tool.poetry]
name = "foo"
version = "1.0.0"
description = ""
authors = ["foo bar"]
packages = [
  {include = "foo", from = "src"},
  {include = "pytest_foo", from = "src"},
]

[tool.poetry.plugins.pytest11]
foo = "pytest_foo"

[tool.pytest.ini_options]
addopts = [
  "--cov-fail-under=80",
  "--cov=foo",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

Run `pytest`:
```sh
tests/test_foo.py .                                                                                                                                                                                                                                                      [100%]

---------- coverage: platform darwin, python 3.7.13-final-0 ----------
Name                  Stmts   Miss  Cover
-----------------------------------------
src/foo/__init__.py       2      1    50%
-----------------------------------------
TOTAL                     2      1    50%

FAIL Required test coverage of 80% not reached. Total coverage: 50.00%
```

## Versions

```sh
pytest==7.2.2
pytest-cov==4.0.0
```
