### ISSUE TITLE
Memory Leak Python 3.12.2

### ISSUE THREAD

**Issue by 0x78f1935** [pytest-dev/pytest-cov#628]
# Summary
I conducted several tests with Python 3.11 with success and recently migrated to Python 3.12. I observed that on my Debian system, the SSH connection is lost after running my GitHub Actions pipeline. This issue consistently occurs after all tests have completed, and the results are about to be fetched.

Upon further investigation, I was able to reproduce this problem on a Windows system running Visual Studio Code.

As the repository is private, I will provide as much information as possible in this ticket to aid in troubleshooting.

![image](https://github.com/pytest-dev/pytest-cov/assets/14298262/3a975298-b69b-4c3d-93d6-4795f6f51d47)

**Note:** This issue persists until all available memory has been used.

The terminal is stuck at:

![image](https://github.com/pytest-dev/pytest-cov/assets/14298262/d8c43cdd-9cb7-4abf-b81d-e10c86d86494)

When I develop on my remote server and this happens, SSH simply times out. When I run this on my desktop, I can barely use my computer due to the memory leak, which prevents me from stopping the generation of the coverage.

During my investigation, I toggled various settings within my test suite and did the same with libraries. I removed xdist because I thought it might be related to multiprocessing, but this was not the case. What remained was:

```
django-coverage-plugin==3.1.0
    # via -r requirements.in
pytest==8.0.0
    # via
    #   pytest-cov
    #   pytest-django
    #   pytest-sugar
pytest-cov==4.1.0
    # via -r requirements.in
pytest-django==4.8.0
    # via -r requirements.in
pytest-sugar==1.0.0
    # via -r requirements.in
python-dotenv==1.0.1
    # via -r requirements.in
```

I'm utilizing `pyproject.toml` and use various flags to start my tests.

```
[tool.pytest.ini_options]
addopts = "--exitfirst -vs --junitxml htmlcov/pytest.xml --cov --cov-report html --cov-report xml --cov-report term"
```

which should results into: `python -m pystest --exitfirst -vs --junitxml htmlcov/pytest.xml --cov --cov-report html --cov-report xml --cov-report term`

Note: When running in Python3.11 this works fine.

When running on Python3.12 with only the flags `python -m pystest --exitfirst -vs` everything runs fine.
![image](https://github.com/pytest-dev/pytest-cov/assets/14298262/c162a588-b8d7-480c-8447-682820c5509c)

You might have noticed by now this is a django application. When running the same tests but with the django suite, everything works fine, even in Pyhton3.12. The command would look like `python manage.py test --debug-mode --noinput --pythonpath backend`
![image](https://github.com/pytest-dev/pytest-cov/assets/14298262/d2344a0f-c710-4406-b192-63504d7a9408)

Note: The last two images do not generate coverage data. (Django test suite and Pytest without coverage)

## Expected vs actual result

I expect my tests to run just like Python3.11 without memory issues.

# Reproducer

I don't necesarely have a reproducable environment, but I do have a [base image](https://hub.docker.com/repository/docker/annihilator708/django-react-base/general) which I use for my Django application. All requirements are in there eventho I listed them already. This image doesn't include any tests.

## Versions

```
django-coverage-plugin==3.1.0
    # via -r requirements.in
pytest==8.0.0
    # via
    #   pytest-cov
    #   pytest-django
    #   pytest-sugar
pytest-cov==4.1.0
    # via -r requirements.in
pytest-django==4.8.0
    # via -r requirements.in
pytest-sugar==1.0.0
    # via -r requirements.in
python-dotenv==1.0.1
    # via -r requirements.in
```
Python 3.12.2

## Config

Do note the usage of `-n 8`, which was originally employed for xdist and has already been removed from my configuration to exclude xdist from the problem.

Original config

```toml
[tool.pytest.ini_options]
addopts = "-n 8 --exitfirst -vs --junitxml htmlcov/pytest.xml --cov --cov-report html --cov-report xml --cov-report term"
testpaths = [
    "tests.py",
    "test_*.py",
    "*_tests.py",
]
DJANGO_SETTINGS_MODULE = "backend.application.settings"
norecursedirs = "frontend/src/*"

[tool.coverage.run]
branch = true
command_line = "-m pytest"
concurrency = [
    "multiprocessing",
    "thread",
]
parallel = true
source = [
    "backend",
]
omit = [
    "*.html",
    "*.txt",
    "*.log",
    "*.js",
    "*.cjs",
    "*.jsx",
    "*.json",
    "*.ts",
    "*.tsx",
    "*.css",
    "*.sass",
    "backend/application/management/commands/clear_migrations.py",
    "backend/application/pagination.py",
    "backend/application/serializers.py",
]
plugins = ["django_coverage_plugin", ]

[tool.coverage.report]
fail_under = 90
ignore_errors = false
precision = 2
show_missing = true
skip_covered = false
skip_empty = true
sort = "Cover"

[tool.coverage.html]
directory = "htmlcov"
show_contexts = true
skip_covered = false
skip_empty = true
title = "Backend-code Coverage"

[tool.coverage.xml]
output = "htmlcov/coverage.xml"

[tool.coverage.django_coverage_plugin]
template_extensions = 'html, txt, tex, email'
```

## Code

An example how my tests might look like:

```python
# -*- mode: python ; coding: utf-8 -*-
"""
Unit Test: Application
----------------------
"""
from django.test import TestCase
from backend.application import get_logger
from uuid import uuid4


class LoggerTests(TestCase):
    def test_obtaining_logger(self):
        """
        Check if application is able to import the logger.
        """
        name = str(uuid4())[20:]
        logger = get_logger(name)
        self.assertEqual(logger.name, name)
```

**Comment by nicoddemus** [comment]
There's been some known performance problems with coverage on Python 3.12, might be related:

https://github.com/nedbat/coveragepy/issues/1665#issuecomment-1937075835
https://github.com/python/cpython/issues/107674

Perhaps try using `COVERAGE_CORE=sysmon` from [`7.4.0`](https://coverage.readthedocs.io/en/7.4.1/changes.html#version-7-4-0-2023-12-27), might help.

**Comment by 0x78f1935** [comment]
Hi @nicoddemus! Thank you for referring to those references.

I've played around with my configuration, and so far, I have the following to document.

## Attempt 1

> Perhaps try using `COVERAGE_CORE=sysmon` from [`7.4.0`](https://coverage.readthedocs.io/en/7.4.1/changes.html#version-7-4-0-2023-12-27), might help.

This was the most straightforward thing to try. I changed my `.vscode` config to the following.

```json
{
    "name": "Test: Pytest",
    "type": "python",
    "request": "launch",
    "module": "pytest",
    "env": {
        "PYDEVD_DISABLE_FILE_VALIDATION": "1",
        "COVERAGE_CORE": "sysmon"
    },
    "justMyCode": true
}
```

And made sure to disable "branch" in my pyproject.toml file.

```toml
[tool.coverage.run]
# Whether to measure branch coverage in addition to statement coverage
branch = false
```
The documentation states it doesn't work for branch coverage, therefor I turned it off.

While keeping an eye on my memory usage, I'm writing this message with 18% in use while my tests are running on my Windows 11 system. After my tests hit 100%, the memory usage skyrockets like before.

![image](https://github.com/pytest-dev/pytest-cov/assets/14298262/4fd85879-d4c0-4822-b5d3-1b47f7db3b27)

### Conclusion

I don't think `COVERAGE_CORE=sysmon` solves my issue. But lets leave it on for now.

## Attempt 2

> There's been some known performance problems with coverage on Python 3.12, might be related:
> 
> [nedbat/coveragepy#1665 (comment)](https://github.com/nedbat/coveragepy/issues/1665#issuecomment-1937075835) \
> [python/cpython#107674](https://github.com/python/cpython/issues/107674)
> 

I'm aware that CPython underwent significant changes from version `3.10` to `3.11` to `3.12`. It could be related, but it's uncertain at this point... :C. Let's try removing coverage from my stack and see where this goes!

I removed `pytest-cov==4.1.0` from my stack, including `django-coverage-plugin==3.1.0`.

I removed `--cov --cov-report html --cov-report xml --cov-report term` from `addopts` located in my pyproject.toml.

```toml
[tool.pytest.ini_options]
addopts = "--exitfirst -vs --junitxml htmlcov/pytest.xml"
```

I also removed the django plugin `"django_coverage_plugin"` from my toml file.

```toml
plugins = []
```

Time to try again.

### Conclusion

![image](https://github.com/pytest-dev/pytest-cov/assets/14298262/63ead3f9-a625-4a6d-987b-a79f7ea0858c)

That worked. Something is up with either `pytest-cov==4.1.0` or `django-coverage-plugin==3.1.0`.

## Attempt 3

I'll reinstall `pytest-cov==4.1.0`, but let's run the tests without any additional flags.

```sh
Installing collected packages: pytest-cov
Successfully installed pytest-cov-4.1.0
```

Lets fire it up!

### Conclusion

![image](https://github.com/pytest-dev/pytest-cov/assets/14298262/172a770c-974d-4dc2-9c00-1d60d6d38d41)

That also works. Let's add the first flag back but without adding the django plugin.

## Attampt 4

I added `--cov --cov-report html` to the `addopts` variable located in my pyproject.toml and re-ran my tests.

### Conclusion

![image](https://github.com/pytest-dev/pytest-cov/assets/14298262/860358be-507a-4a9f-a67f-a36f77c37547)

So we are back at square one.

### Attempt 5

Let's remove `--cov --cov-report html` and add `--cov --cov-report xml` instead; maybe that makes a difference.

### Conclusion

![image](https://github.com/pytest-dev/pytest-cov/assets/14298262/36c90184-26c6-4de5-8a8c-a93db1e26a42)

No luck.

### Attempt 6

Perhaps the `--cov` command is the issue here; let's try to remove that instead and try again.

My `addopts` looks like this right now:

```toml
[tool.pytest.ini_options]
addopts = "--exitfirst -vs --junitxml htmlcov/pytest.xml --cov-report xml"
```

### Conclusion

I'm surprised...

![image](https://github.com/pytest-dev/pytest-cov/assets/14298262/259ec800-a6c4-4471-a6f1-b6863389d32b)

I was already writing my overall conclusion, but let's try to add the HTML report back!

### Attempt 7

My `addopts` looks like this right now:

```toml
[tool.pytest.ini_options]
addopts = "--exitfirst -vs --junitxml htmlcov/pytest.xml --cov-report html --cov-report xml"
```

### Conclusion

HOLYMOLY THAT WORKED!. ... Is what I thought..

![image](https://github.com/pytest-dev/pytest-cov/assets/14298262/841f029c-934b-477f-8292-866418937bd6)

![image](https://github.com/pytest-dev/pytest-cov/assets/14298262/2863bfd6-05c0-4d37-a772-b7597ba5f97e)

Only the XML file actually generated.

# Overall Conclusion

As mentioned in [this ticket](https://github.com/pytest-dev/pytest/issues/11969), I could run the Django test suite without coverage, but that doesn't work for my pipeline. I need the XML file for my pipeline! So just a few adjustments in the `addopts` variable should do the trick for me and solve my issue.

I'm not sure if I can be convinced that CPython is the issue here. My testing really points to the HTML generation of `pytest-cov`, which I like to utilize locally for development purposes.

**Comment by nicoddemus** [comment]
Hi @0x78f1935,

Sorry it is late so I kinda skimmed through your post, but before going to bed I decided to leave another suggestion you can try: have you tried using `coverage` directly (`coverage run -m pytest`), without using `pytest-cov`? This would help nail down if this is something related to `pytest-cov` or `coverage` itself.

**Comment by 0x78f1935** [comment]
Hi @nicoddemus,

No worries! I really appreciate your time. Thank you for your response!

I tried your suggestion!

Firstly, I added the following section to my .vscode/launch.json:
```json
{
    "name": "Test: Pytest Coverage directly",
    "type": "python",
    "request": "launch",
    "module": "coverage",
    "args": [
        "run",
        "-m",
        "pytest",
    ],
    "env": {
        "PYDEVD_DISABLE_FILE_VALIDATION": "1",
        "COVERAGE_CORE": "sysmon"
    },
    "justMyCode": true
},
```

My **addopts** currently looks like this:
```toml
[tool.pytest.ini_options]
addopts = "--exitfirst -vs --junitxml htmlcov/pytest.xml --cov-report xml"
```

![image](https://github.com/pytest-dev/pytest-cov/assets/14298262/0365a2fe-c400-4a31-9ea8-cd3ab72c13f6)

We know that `--cov` triggered the memory leak. So lets add that!, because right now we are missing some supposed to generated files.

Running it once more results into:

![image](https://github.com/pytest-dev/pytest-cov/assets/14298262/154f9a87-139f-4591-8f5e-c01f4f21ad65)

Unfortunately, the same issue. To make double sure, I'll remove Visual Studio Code out of the equation in the hope I can ctrl + c out of the memory leak.

Running `coverage run -m pytest` in my terminal results in:

![image](https://github.com/pytest-dev/pytest-cov/assets/14298262/22a76f5f-f76f-411d-9166-9612f7d904f5)

And it keeps rising.

I straightup forgot to remove `pytest-cov` like you suggested, so lets head back to vscode and uninstall `pytest-cov`. I removed `--cov --cov-report xml` from my `pyproject.toml`. 

```toml
[tool.pytest.ini_options]
addopts = "--exitfirst -vs --junitxml htmlcov/pytest.xml
```

Lets run it again.

```sh
    Test session starts (platform: win32, Python 3.12.2, pytest 8.0.0, pytest-sugar 1.0.0)
    cachedir: .pytest_cache
    django: version: 5.0.2, settings: backend.application.settings (from ini)
    rootdir: xxx
    configfile: pyproject.toml
    plugins: anyio-4.2.0, django-4.8.0, sugar-1.0.0
```

![image](https://github.com/pytest-dev/pytest-cov/assets/14298262/e3ddb8ba-89c5-40cf-8768-db0abab9e59f)

That worked.

Lets add back `--cov --cov-report xml`

```toml
[tool.pytest.ini_options]
addopts = "--exitfirst -vs --junitxml htmlcov/pytest.xml --cov --cov-report xml
```

And try again!

```sh
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --cov --cov-report
  inifile: xxx\pyproject.toml
  rootdir: xxx
```

So lets remove `--cov --cov-report xml` again and see if `junitxml` generates.

![image](https://github.com/pytest-dev/pytest-cov/assets/14298262/9c1e2eed-9a30-42e8-ad68-0cb45e48720d)

![image](https://github.com/pytest-dev/pytest-cov/assets/14298262/1c0b0e26-5644-4bc9-a56c-af275b1c2751)

Unfortunately no luck
