### ISSUE TITLE
Configuring automatically output XML reports in pyproject.toml

### ISSUE THREAD

**Issue by kubotty** [pytest-dev/pytest-cov#654]
# Summary
I would like to configure my pyproject.toml settings to output an XML report when running `pytest --cov`,without having to specify the `--cov-report xml` option.

I'm seting the "run", "report", and "xml" options in my pyproject.toml file.
Additionaly, I think also output type should be able to be defined in the pyproject.toml file.

I tried to write it in `addopts` of `tool.pytest.ini_options`, but it is always applied regardless of whether or not I include the `--cov` option. This is inconvenient in my project. 
(My project requires testing with also Python 3.7, so I have restricted pytest-cov by "pytest-cov; python_version >= '3.8'" in dependencies block.)

I have searched the documentation for options both in this documentation and the coverage documentation, but have not found any. If such an option exists, could you please let me know?

I have attached my pyproject.toml below.

```toml
# Settings for pytest
[tool.pytest.ini_options]
filterwarnings = [
]
testpaths = ["tests"]


# Settings for coverage
[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
exclude_lines = [
    "if TYPE_CHECKING:",
    "except ImportError:",
]
show_missing = true

[tool.coverage.xml]
output = "coverage.xml"
```
