### ISSUE TITLE
Add markdown output support

### ISSUE THREAD

**Issue by beck3905** [pytest-dev/pytest-cov#688]
# Summary

I understand that pytest-cov uses coverage.py under the hood and coverage.py supports `--format=markdown` as an output option. Could this be added as an output format in pytest-cov?

This would be helpful adding the test report to a GitHub Actions Job Summary, which requires markdown format.

**Comment by nedbat** [comment]
You can run `coverage report --format=markdown` as a second command and get the output without changing pytest-cov at all.

**Comment by alelom** [comment]
We definitely could use this feature -- getting a markdown output would make it fast to display the coverage report from github, as a fast result from a github action.

**Comment by webknjaz** [comment]
I think there's no harm in having this setting. Though, it's most useful within GHA when appending to the output file, not rewriting it. So `--cov-report markdown:"${GITHUB_STEP_SUMMARY}"` doesn't feel enough — it's unclear how one could specify that the file in the env var should be open in append mode?

**Comment by nedbat** [comment]
@marcosboger I'm not a maintainer here so it's not my decision. And as I mentioned in my comment, I'm generally not in favor of jamming more features into this tool when the same thing can already be done in a simple way without adding maintenance burden here.

**Comment by alelom** [comment]
> the same thing can already be done in a simple way without adding maintenance burden here.

I have yet to find a simple way to do this in my CI/CD workflows. If this feature was added in the same package it would be a game changer for me. Would you be able to share how can it be done in a simple way? Honestly curious, not provoking, I would really appreciate it.

**Comment by marcosboger** [comment]
@webknjaz I believe in that case, the user should probably leverage [Multiline Markdown content](https://docs.github.com/en/enterprise-cloud@latest/actions/reference/workflows-and-actions/workflow-commands#multiline-markdown-content) capturing the output from the command and `>>` that to `$GITHUB_STEP_SUMMARY`. But that should be done directly by the user configuring this in GHA, so I think no different behavior from pytest-cov needed. What do you think?

**Comment by beck3905** [comment]
I was able to accomplish what I needed using the following composite action that leverages some other community actions:

```
runs:
  using: composite
  steps:
    - name: Run Pytest with Coverage
      shell: bash
      run: |
        poetry run pytest --junitxml=test-report/test-report.xml --cov=. --cov-report=html:coverage/htmlcov --cov-report=xml:coverage/coverage.xml --cov-report=term-missing

    - name: Publish Test Report
      uses: ctrf-io/github-test-reporter@v1
      if: always()
      with:
        report-path: test-report/test-report.xml
        github-report: true
        integrations-config: '{"junit-to-ctrf": {"enabled": true, "action": "convert"}}'

    - name: Build Pytest Report
      id: test-report
      if: always()
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-xml-coverage-path: coverage/coverage.xml
        junitxml-path: test-report/test-report.xml
        hide-comment: true

    - if: always()
      shell: bash
      run: |
        echo "---" >> $GITHUB_STEP_SUMMARY
        echo "# Coverage Report" >> $GITHUB_STEP_SUMMARY
        echo -e ${{ steps.test-report.outputs.summaryReport }} >> $GITHUB_STEP_SUMMARY
```
